### ISSUE TITLE
Redeem button has no effect on the ExchangeDetails page

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/interface#1012]

**Comment by levalleux-ludo** [comment]
In the previous version (ex: tag v0.0.280), before the merge with the Commit Widget, the function bosonWidgetReload() (implemented in the widget script) is called to ensure the click handler is attached to the Redeem button.
With the current version, the call to bosonWidgetReload() has disappeared from the dApp and can't be find either in the react-kit.

**Comment by sukrita3** [comment]
looks good
