### ISSUE TITLE
DR Center - Seller point of view - reformulate the counter proposition text

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/interface#1043]
When a seller wants to make a counter proposition in the DR center, I think the following text should be reformulated (from the Seller point of view), Something like "The buyer will keep the purchased product and get a partial refund":
![image](https://github.com/bosonprotocol/interface/assets/7184124/d2dac68c-27d9-4c1d-a42b-55a21f219c08)

**Comment by albertfolch-redeemeum** [comment]
@sukrita3 what should the text say?

**Comment by sukrita3** [comment]
The buyer will keep the purchased product and also get a partial refund.
