### ISSUE TITLE
zoid is not defined when opening the Redeem widget

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/interface#1067]
There is no consequence for the user, but this error appears in the dApp log when the Buyer clicks on Redeem or Cancel on an Exchange 
![image](https://github.com/bosonprotocol/interface/assets/7184124/6fda447b-c211-411a-8f8d-e29d2d6f2759)

**Comment by albertfolch-redeemeum** [comment]
fixed in the latest release of widgets
