### ISSUE TITLE
update design homepage

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#1104]
https://www.figma.com/design/XJTJYx5N9gsYSHTfL1167P/Roblox-Widget-%26-Landingpage?t=gIBYcXCALXkpxHyr-0

![Image](https://github.com/user-attachments/assets/a5377267-a50a-4ff1-bd74-d8949b65c204)

**Comment by albertfolch-redeemeum** [comment]
to be done by Max

**Comment by albertfolch-redeemeum** [comment]
the images that you see in the "Tokenize, transfer..." part are not hardcoded, they should come from a list of curated offers

**Comment by albertfolch-redeemeum** [comment]
when the seller card is updated, the seller card in the explore page should also be updated
same with product card

**Comment by sukrita3** [comment]
![Screenshot 2024-10-17 at 14 49 33](https://github.com/user-attachments/assets/8a2a21b0-78dd-426f-b3fb-41192d4023af)
Is it possible to add the shadow to the background like in Figma?

**Comment by sukrita3** [comment]
![Screenshot 2024-10-17 at 14 51 02](https://github.com/user-attachments/assets/17869ddf-2fac-4307-94c1-05b65d11f291)
Check font size, not the same as in Figma

**Comment by sukrita3** [comment]
![Screenshot 2024-10-17 at 14 54 06](https://github.com/user-attachments/assets/867c0be0-30c0-4bbe-83d0-a487cbfcd2c6)
Check font size in these cards

**Comment by sukrita3** [comment]
![Screenshot 2024-10-17 at 14 54 43](https://github.com/user-attachments/assets/0a078885-07bf-4ed2-97c6-3d6c45a3ea27)
Font size needs to change

**Comment by sukrita3** [comment]
![Screenshot 2024-10-17 at 15 00 26](https://github.com/user-attachments/assets/9704a7a5-0f8d-42e0-85fc-3007713d1a1f)
Check font size

**Comment by sukrita3** [comment]
@albertfolch-redeemeum do we need to implement the "curation list" for the assets to display on the home page tile?

**Comment by sukrita3** [comment]
![Image](https://github.com/user-attachments/assets/139bced1-096b-4a7d-8a9b-e1c7dbd00c16)
the h1 and subline should be in a div that fills the space, so the button is pushed down in the block

**Comment by sukrita3** [comment]
![Image](https://github.com/user-attachments/assets/1adca7ef-5b17-410f-87a5-48cd4c28d33a)
navbar buttons have no side padding

**Comment by sukrita3** [comment]
![Image](https://github.com/user-attachments/assets/7ae687c1-f28a-47eb-82dc-1202af41a838)
the group cards have shadow on them, that shouldn’t be

the item cards have shadow on them when hovered, that shouldn’t be
