### ISSUE TITLE
Multiple variants, deletion of one breaks the expereince

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#564]
If 2 variants have been added, and one is removed, the option to add information for one variant is no longer available.

**Comment by albertfolch-redeemeum** [comment]
@sukrita3 can you attach some screenshots to reproduce it?

**Comment by sukrita3** [comment]
![Image](https://user-images.githubusercontent.com/122606799/227170410-10618f81-25e4-43c3-a596-a8247464676d.png)



![Image](https://user-images.githubusercontent.com/122606799/227170429-4e6f3e70-f5ca-4310-b32a-87d8e975c822.png)

From the screenshots, one notices that when the colour variant was completely removed, the size variants do no remain.

**Comment by albertfolch-redeemeum** [comment]
![image](https://user-images.githubusercontent.com/102516373/227187509-385e0d62-b382-4e83-8faf-0d437efc7d8a.png)

that is already fixed in https://interface-test.on.fleek.co/ but not in prod (yet) so closing this issue
