### ISSUE TITLE
Token Box UX when defining variants

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#565]
During offer create, when defining the variants, the token box gets cut off.

**Comment by albertfolch-redeemeum** [comment]
if the window is big enough it looks good 
![image](https://user-images.githubusercontent.com/102516373/227168278-a84b5efe-eee7-4732-a861-3455459fc7e7.png)

when it's like an ipad, then it gets cut off but these pages are meant to be used in a laptop/desktop so Id say we can close this, up to you @sukrita3 
![image](https://user-images.githubusercontent.com/102516373/227168657-64f7424e-6e3b-48a3-a970-3ad022ccf8b3.png)

**Comment by sukrita3** [comment]
Even on full screen mode on my desktop, BOSON gets cut off. 

![Image](https://user-images.githubusercontent.com/122606799/227171407-6af53a54-bf52-4650-a7dc-5880739a0a95.png)

**Comment by albertfolch-redeemeum** [comment]
can you check again in https://github.com/bosonprotocol/interface/pull/572? @sukrita3

**Comment by sukrita3** [comment]
@albertfolch-redeemeum the token box seems to work but I caught another UX issue ... the qty box becomes misaligned if the token amount is empty. 


![Image](https://user-images.githubusercontent.com/122606799/227978010-c39e0455-2362-4f68-87c3-d67f4d68ea46.png)

**Comment by sukrita3** [comment]
Looks good, thanks
