### ISSUE TITLE
Remove non-essential fields from Storefront

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#573]
The storefront feature has some fields that were needed for Brandverse and can be removed from the main experience. 

![Screenshot 2023-03-23 at 15 43 40](https://user-images.githubusercontent.com/122606799/227239561-67109e4c-0219-4704-b305-6874c522388c.png)

**Comment by albertfolch-redeemeum** [comment]
I removed only the inputs Commit Proxy Address and Link to collection/contract (so 2 inputs) @sukrita3

**Comment by sukrita3** [comment]
Looks good @albertfolch-redeemeum 

![Image](https://user-images.githubusercontent.com/122606799/228214500-ff9ae47f-de21-409a-9913-592f261735fd.png)
