### ISSUE TITLE
Block FATF States from Country Drop down in Redemption

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#585]
In the Redemption workflow, remove the FATF countries from the list.

**Comment by albertfolch-redeemeum** [comment]
as discussed, what we want is to keep the countries in here (except for Russia):

![image](https://user-images.githubusercontent.com/102516373/231454385-7a99379d-84f8-4c5f-93d2-6a802c7183e6.png)

source: https://www.fatf-gafi.org/en/home.html

**Comment by albertfolch-redeemeum** [comment]
@sukrita3 check the linked PR

**Comment by albertfolch-redeemeum** [comment]
requirements are actually: show FATF countries (except Russia as I said above) in the redemption modal in the country input (right now it's a free text input instead of a dropdown). The country phone selector shouldnt change

**Comment by sukrita3** [comment]
Address form only shows the FATF countries so we can close.
