### ISSUE TITLE
DDOS protection when creating a custom storefront

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/interface#589]
potential for a malicious user to DDOS our app when creating a custom storefront

**Comment by albertfolch-redeemeum** [comment]
this might be useful 
![image](https://user-images.githubusercontent.com/102516373/231469349-8e0973b6-59af-4e67-b817-81f6aa951e2e.png)

**Comment by albertfolch-redeemeum** [comment]
@levalleux-ludo @sukrita3 let's discuss what to do about this on next Monday

**Comment by sukrita3** [comment]
Looks good
