### ISSUE TITLE
edit profile lens -> no lens and vice versa

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#616]

**Comment by sukrita3** [comment]
Profile creation fields should be consistent with the capitalisation of letters.

**Comment by sukrita3** [comment]
Copy Change
Old: Put your most frequently used online channel in here. Use the URL for Social media. 
New: Add a website or your mostly frequently used social media link.

![Screenshot 2023-05-10 at 16 51 45](https://github.com/bosonprotocol/interface/assets/122606799/7b7cf9d7-443d-4e79-a806-3a3e2fcc8d45)

**Comment by sukrita3** [comment]
Copy Change
Old: You are creating a seller account in Boson Protocol. Input the relevant information relating to your secondary royalty 
New: You are creating a seller account on Boson Protocol. Input the relevant information relating to your secondary royalties.
![Screenshot 2023-05-10 at 14 27 35](https://github.com/bosonprotocol/interface/assets/122606799/a0ea67b5-644d-4c4f-ad3d-bf161981969d)

**Comment by sukrita3** [comment]
Copy Change
Old: Address for Royalty payment
New: Address for royalty payments

![Screenshot 2023-05-10 at 14 28 11](https://github.com/bosonprotocol/interface/assets/122606799/4e54196d-02f8-4e12-917b-76d72d4f1301)

**Comment by sukrita3** [comment]
Copy Change
Old: For your journey as a seller reputation is key. Boson Protocol allows sellers to directly link their Lens profile to their Boson account.
New: Confirm Profile Information _(as a header)_
![Screenshot 2023-05-10 at 14 29 15](https://github.com/bosonprotocol/interface/assets/122606799/7c424808-f722-4620-bb18-cd77d6af9e6a)

**Comment by sukrita3** [comment]
Update Profile Creation Header and change 'Link Lens Profile' to toggle if possible

![Screenshot 2023-05-10 at 18 33 02](https://github.com/bosonprotocol/interface/assets/122606799/9d3e6d4c-e2bb-4b98-8f79-5335b224db98)

**Comment by sukrita3** [comment]
Update copy and add button to resume creation without Lens

![Screenshot 2023-05-10 at 18 37 42](https://github.com/bosonprotocol/interface/assets/122606799/ff5b28b5-f36c-4890-9db2-fffbc55521b8)

**Comment by sukrita3** [comment]
**1) Copy**
OLD: Link Lens profile
NEW: Link Lens Profile

**2) UX**
Can we make the font size and toggle a bit smaller please? Also, maybe the colour font colour to purple? 
![Screenshot 2023-05-11 at 15 13 39](https://github.com/bosonprotocol/interface/assets/122606799/b316d3fd-42da-4f34-b410-8b0d2ae62d7f)

**Comment by sukrita3** [comment]
Copy
OLD: Your brand / Name
NEW: Your brand / name

![Screenshot 2023-05-11 at 15 15 19](https://github.com/bosonprotocol/interface/assets/122606799/3e5ff530-d64c-4a01-a17a-580c96b487a2)

**Comment by sukrita3** [comment]
**1) Copy**
OLD: Boson Protocol allows sellers to directly link their Lens profile to their Boson account. If you wish to create a Lens profile, please go to https://claim.lens.xyz/ If you already have a Lens profile, they will be shown below.
NEW: You can directly link your Lens profile to your Boson account. If you wish to create a Lens profile, please go to https://claim.lens.xyz/. 
If you already have a Lens profile, it will be shown below.

**2) Copy**
OLD: No lens profiles found
NEW: No Lens profiles found

**3) UX**
Can we make the font size smaller and maybe in grey for 'No Lens profiles found'?

**4) UX**
Can we make the 'Proceed without Lens' a box (i.e. with borders) when there is no hover?
![Screenshot 2023-05-11 at 15 17 18](https://github.com/bosonprotocol/interface/assets/122606799/7bd4fb38-557b-45e9-b291-8238fc98e37c)

**Comment by sukrita3** [comment]
Copy- Drop Caps
Cover picture
Contact e-mail
Secondary royalties 
![Screenshot 2023-05-11 at 15 19 15](https://github.com/bosonprotocol/interface/assets/122606799/21762b8d-7293-450f-b478-3f03c11fdc99)

**Comment by sukrita3** [comment]
1) Change heading to Communication Method
2) Dropdown Options should be: 1) XMTP initialisation + e-mail 2) XMTP end-to-end
3) Copy for description: Specify how you would like to communicate with your buyers after they redeem their item. Initial communication along with a buyer’s delivery address will be sent via XMTP.
![Screenshot 2023-05-11 at 15 15 51](https://github.com/bosonprotocol/interface/assets/122606799/5d240813-629b-43d2-bb3b-3b6a5380c27e)

**Comment by sukrita3** [comment]
Copy: Add a website or the link to your most frequently used social media here.

![Screenshot 2023-05-11 at 15 16 23](https://github.com/bosonprotocol/interface/assets/122606799/56ca4049-3835-4b61-97ee-db0db01e9b30)

**Comment by sukrita3** [comment]
Copy Change
Old: Communication Method 
New: Communication method

Old: Specify how you would like to communicate with your buyers after they redeem their item. Initial communication along with a buyer's delivery address will be sent via XMTP.
New: The buyer's delivery address will be sent to you via the dApp's chat function (XMTP). For further communication, like sending tracking IDs or receiving inquiries from buyers about their order status, specify your preference: continuing on XMTP (chat) or switching to e-mail.

Drop Down:
Chat (XMTP) for delivery information; e-mail after
Chat (XMTP) for all buyer communication

**Comment by sukrita3** [comment]
![Screenshot 2023-05-15 at 17 18 10](https://github.com/bosonprotocol/interface/assets/122606799/4c23df7b-1bd0-4c1a-99ae-3e95330e1c16)
lower case

**Comment by sukrita3** [comment]
![Screenshot 2023-05-15 at 17 21 25](https://github.com/bosonprotocol/interface/assets/122606799/14ad2439-1196-4402-a11a-e603ce3e89e7)
It would be great to have the minimum as 30 in the box and not "1"

**Comment by sukrita3** [comment]
![Screenshot 2023-05-16 at 12 34 13](https://github.com/bosonprotocol/interface/assets/122606799/cd5be4e8-e87e-4f32-8f9f-c20a60e5a02b)
Above 'Create your Profile' add 'To begin selling on the BosonApp, start by creating a profile and seller account'
(Body text size)

**Comment by sukrita3** [comment]
Preview of multivariant offer does not show variant picker
