### ISSUE TITLE
dApp Copy Changes

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#625]
Change spelling of email from e-Mail or e-mail to email on profile creation form.

**Comment by sukrita3** [comment]
Change copy on Communication method, content TBD

**Comment by sukrita3** [comment]
![Screenshot 2023-05-15 at 14 01 28](https://github.com/bosonprotocol/interface/assets/122606799/92870b14-7000-4be5-8997-e9c324f6b677)
REMOVE: By selecting confirm, you agree to pay the above fees, accept the Boson seller agreement and Payments Terms of Use acknowledge reading the User Privacy Notice and assume full responsibility for the item offered and the content of your listing

OLD: You wont be able to make changes after confirming
NEW: Royalty share and payment information cannot be changed after creating your seller account. 
Profile information can be edited or changed at anytime.

**Comment by sukrita3** [comment]
Help Copy Changes (changes in bold)

What is **a** phygital?

Why would I sell a phygital item?This new asset form bridges the physical and digital world, allowing your products to hit new levels of utility and reach an **ever-growing** new audience.

What is an **exchange policy**?The exchange policy covers **both the** contractual and **the** protocol terms of the exchange to protect buyer and seller. This includes obligations of both parties to follow **through** with their commitment, and evidence requirements in case there is a dispute.The policy also includes fair protocol terms, to make it easy for sellers to set-up a fair exchange.

What is a **token gated offer**?

What is a **dispute resolver**?If a buyer raises and escalates a dispute, the dispute resolver **steps** in to resolve the dispute. Both buyer and seller will be asked to submit evidence based on the nature of the dispute.

How long should the **redemption** period be?

What **happens** when the **offer ends**?

What is **the** buyer cancel penalty?

**Comment by albertfolch-redeemeum** [comment]
> ![Screenshot 2023-05-15 at 17 39 07](https://user-images.githubusercontent.com/122606799/238725346-b91cf74f-7b3a-4404-849b-04e085b78c23.png) Change Copy and maybe UX (let's discuss) OLD: You need to top up your seller deposit pool Currently, your product can't be bought becasue the balance in your seller deposit pool is not sufficient enough
> 
> NEW: Top up your seller deposit pool! Currently, your product can't be purchased because the funds in your seller deposit pool is insufficient.

copy changed, UX pending to be discussed

**Comment by sukrita3** [comment]
![Screenshot 2023-05-18 at 10 45 37](https://github.com/bosonprotocol/interface/assets/122606799/f781119f-0082-4385-a998-9408a71f06d4)
In the box for Description, replace 'Describe' with 'Tell people more about your brand'

**Comment by sukrita3** [comment]
![Screenshot 2023-05-18 at 10 51 44](https://github.com/bosonprotocol/interface/assets/122606799/1d70dfd3-5d89-47f0-aee6-9ba2957b1442)
OLD: Different Variants
NEW: Different variants

**Comment by sukrita3** [comment]
![Screenshot 2023-05-18 at 10 52 16](https://github.com/bosonprotocol/interface/assets/122606799/23b02dba-5240-486d-9c4d-556473ad3981)
OLD: 
Description *
Describe your product. Provide as much detail as possible
Describe

NEW:
Description *
Describe your product with as much detail as possible. 
Include information like shipping is included, or whether duties/taxes are covered.

**Comment by sukrita3** [comment]
Maybe we can merge into one box?
OLD: To proceed you must first initialize your chat client
NEW: To proceed, first initialize your chat client that enables two way communication with buyers and receiving delivery details. 
![Screenshot 2023-05-18 at 11 59 55](https://github.com/bosonprotocol/interface/assets/122606799/5bd69ed4-a5ad-4e22-9f78-a354f64b52ae)

**Comment by sukrita3** [comment]
New copy for communication method:

Heading:
Ongoing Communication method

Description:
First-time Communication: Initially, the buyer’s delivery address will always be sent to you via the dApp’s chat function (XMTP). 
Ongoing communication:  please choose between - continuing on chat (XMTP) or switching to email. (Used for sending tracking IDs or receiving inquiries from buyers about their order status.)

Ongoing communication method:
Chat (XMTP)
Email

**Comment by albertfolch-redeemeum** [comment]
all done
