### ISSUE TITLE
revisit footer

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#635]
first suggestion of links in the footer:

Buy
Explore
Chat
Dispute

Sell
Create Product
Create Storefront
Chat
Dispute

**Comment by sukrita3** [comment]
Here are some changes to the footer
https://miro.com/app/board/uXjVMHtnUIg=/

**Comment by mischat** [comment]
I think that the footer should be context sensitive, i.e. if the buyer doesn't have any exchanges, we shouldn't link to the empty sections of the dapp. We should only link to disputes if a buyer has things in the redeem phase, and for chat messages, I don't think that we should link to the section until a buyer has an exchange... cc @sukrita3 and @albertfolch-redeemeum

**Comment by albertfolch-redeemeum** [comment]
- Explore: show always
- View exchanges: if you are a buyer (you have any exchange in any state) and shows the buyer profile
- View transactions: if you are a buyer
- Create Products: if you are a seller
- Seller dashboard: if you are a seller
- Seller profile: if you are a seller
- Chat: if you are either a buyer or a seller and have an exchange
- Dispute center: if you are either a buyer or seller or dispute resolver
