### ISSUE TITLE
dApp Sell Everywhere - Sales Channels

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#663]
Issue for sell everywhere release, introduction of sales channels. 

Figma: https://www.figma.com/file/IqwvzHvdDRDld8aGjwxNII/v2-dApp-Master-file-(Copy)?type=design&node-id=12388-116025&t=NqfwWkgkdhIIgBTc-0

**Comment by sukrita3** [comment]
Typeform link: https://form.typeform.com/to/opn9sH8o

Used for Boson Boulevard

**Comment by sukrita3** [comment]
Copy Change:
Ungated

![Image](https://github.com/bosonprotocol/interface/assets/122606799/5aa3f286-d599-4e98-8f28-bc9edbad63d1)

**Comment by sukrita3** [comment]
This copy has not been updated



![Image](https://github.com/bosonprotocol/interface/assets/122606799/3661f1b6-7f4b-40d6-83a2-4493e553ffb2)

**Comment by sukrita3** [comment]
This one is a bit strange with two 'X' maybe we can discuss to see how we make it simpler 

![Image](https://github.com/bosonprotocol/interface/assets/122606799/072c0d32-aa26-44ff-b053-65bc416b52ce)

**Comment by sukrita3** [comment]
When you hover over 'deposit funds' it looks a bit strange. 

![Image](https://github.com/bosonprotocol/interface/assets/122606799/2dfdfce4-b046-48fb-87c1-2f6d07f5615e)

**Comment by sukrita3** [comment]
Drop down to be changed (copy):
- Specific token
- Collection balance

![Image](https://github.com/bosonprotocol/interface/assets/122606799/d0c5c500-5ddf-49ba-93b4-3689a957c474)

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/interface/assets/122606799/bd35f8c1-fd6c-46e0-b704-cbd125efa280)

**Comment by sukrita3** [comment]
Copy Change

![Image](https://github.com/bosonprotocol/interface/assets/122606799/a901b4c4-9004-4023-a63f-649c77dd8ca7)

**Comment by sukrita3** [comment]
The drop down is correct, but the box has a text before clicking on the drop down that is strange

![Image](https://github.com/bosonprotocol/interface/assets/122606799/0cfb2eb7-cd7d-4a31-b0eb-8dd43ce5bc0c)

**Comment by albertfolch-redeemeum** [comment]
done
