### ISSUE TITLE
dApp quick changes

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#665]
Add a conditional * to royalty payment address
![Screenshot 2023-05-30 at 11 23 52](https://github.com/bosonprotocol/interface/assets/122606799/d8934268-51e6-4449-8ff0-4911cec05212)

**Comment by sukrita3** [comment]
- Align cover picture title and logo picture title. 
- Make cover picture bigger / more visible 
![Screenshot 2023-05-30 at 11 24 05](https://github.com/bosonprotocol/interface/assets/122606799/9c6a42c5-31f5-41b7-957a-4568a35559e0)

**Comment by sukrita3** [comment]
Footer on dApp not consistent to design (items should not wrap)

https://miro.com/app/board/uXjVMHtnUIg=/

**Comment by sukrita3** [comment]
![Screenshot 2023-05-30 at 12 00 33](https://github.com/bosonprotocol/interface/assets/122606799/4a3daa75-c3e2-4925-ae0f-0d1fce9c10f7)

Custom Storefront, 'View More' is always in purple ... should change

**Comment by albertfolch-redeemeum** [comment]
all done
