### ISSUE TITLE
Token Gating dApp Experience

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#681]
Enhance Token Gating dApp experience

https://miro.com/app/board/uXjVMDNFjuw=/

**Comment by sukrita3** [comment]
Updated with mocks here: https://miro.com/app/board/uXjVMDNFjuw=/

Same miro, different section

**Comment by sukrita3** [comment]
@albertfolch-redeemeum copy/text has been updated. Also, took out the token gating description as it is not shown anywhere

**Comment by albertfolch-redeemeum** [comment]
done
