### ISSUE TITLE
Sell Everywhere UAT Fixes

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#697]
Copy was updated to stay consistent on all tiles. 

https://www.figma.com/file/IqwvzHvdDRDld8aGjwxNII/v2-dApp-Master-file-(Copy)?type=design&node-id=12556-119455&t=oMPACP8EwFa2XOaG-0

**Comment by sukrita3** [comment]
![Screenshot 2023-06-21 at 10 41 53](https://github.com/bosonprotocol/interface/assets/122606799/b52f5349-78ce-4ec9-a095-d495c74ce119)
 COPY
Capitalization 'Add a sales channel'

**Comment by sukrita3** [comment]
![Screenshot 2023-06-21 at 10 55 28](https://github.com/bosonprotocol/interface/assets/122606799/b39309ba-fb71-4916-bffe-3964d6a93698)

Copy:
Create a physical or phygital product, enriching it with details, such as images and videos

**Comment by sukrita3** [comment]
![Screenshot 2023-06-21 at 11 00 32](https://github.com/bosonprotocol/interface/assets/122606799/c9c1e9e9-fa70-4a76-a476-2b303bbdecb7)

This screen still needs to be updated I think

**Comment by sukrita3** [comment]
New Copy
Which Metaverses can I set up a store in?
Currently, our Metaverse Commerce Toolkit supports setting up a store on your own land or on Boson Boulevard in Decentraland (DCL). We are expanding into other Metaverse and will be supporting setting up stores in many more places.

**Comment by sukrita3** [comment]
New copy:

What are search tags used for?
Search tags are used to help you differentiate your own products or to increase your item’s visibility when a buyer is looking for similar items. Search tags are free form and can include things like shape, style, function, season, etc.

**Comment by sukrita3** [comment]
New copy:

How many images do I need?
While at least one thumbnail image is required, we recommend adding as many images as you can to show your item’s most interesting characteristics.

**Comment by sukrita3** [comment]
New copy:

How long should the redemption period be?
During the redemption period, buyers can trade, transfer, or gift the rNFT. Hence, the longer the redemption period, the more buyers can benefit from the transferable nature of these rNFTs. You, as a seller, also benefit via royalties from these secondary sales.

A buyer can also redeem the rNFT for the physical item anytime during this period, so consider how long you feel comfortable storing this physical item and factor this into the redemption period.

**Comment by sukrita3** [comment]
New copy:

Which networks does token gating work with?
Token gating currently works on Polygon but will soon work on other EVM chains.

**Comment by sukrita3** [comment]
New copy: 
What is an exchange policy?
The exchange policy helps sellers configure their offers in a way that enables fair exchange.  It covers the contractual terms of the exchange, both on-chain and off-chain, defined to protect both the buyer and seller. It includes the obligations of both parties to follow through with their commitment, as well as the evidence requirements in the event of a dispute.

**Comment by sukrita3** [comment]
New copy: 

How long should the dispute period be?
The dispute period should be a minimum of 30 days, post redemption, to meet our fair exchange guidelines.

**Comment by sukrita3** [comment]
New copy:
How long should the return period be?
The return period should be a minimum of 15 days to meet our fair exchange guidelines.

**Comment by albertfolch-redeemeum** [comment]
done
