### ISSUE TITLE
Update ToS & Bu/Se Agreement 

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#716]
Terms for Boson rNFT v1.2: https://docs.google.com/document/d/1Av8xb_fyr7OwCr6GOP-DW0D61OLv39S4QXDPvxfBOys/edit

Buyer and Seller Agreement v1.2: https://docs.google.com/document/d/1k7cgWZwJGEoMmaTzxTnPxKsjpzaCJGSb6w5WsUeKgEY/edit

Note: Page 13 should not be part of the contract on Bu/Se Agreement

**Comment by albertfolch-redeemeum** [comment]
done
