### ISSUE TITLE
Sell Everywhere Bugs

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#717]
When you follow the 'Launch a Metaverse Store' template, after the last steps (setting up DCL), if you exit out of the modal you are taken to the sales channel page. You should be taken to the Seller Center. 

![Screenshot 2023-06-22 at 13 26 14](https://github.com/bosonprotocol/interface/assets/122606799/eda18554-7e32-4420-bb2e-a760c832b765)

**Comment by albertfolch-redeemeum** [comment]
done
