### ISSUE TITLE
DR Center

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#727]
The DR Center Figma is here:

https://www.figma.com/file/IqwvzHvdDRDld8aGjwxNII/v2-dApp-Master-file-(Copy)?type=design&node-id=12757-158530&mode=design&t=QUNfyTf6oP1ro7ro-0

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/interface/assets/122606799/b0bf9011-4fa3-493d-ab95-257f68cb818f)

**Comment by sukrita3** [comment]
Only show second problem description in chat window

**Comment by sukrita3** [comment]
show only last counterproposal sent on timeline on right

**Comment by sukrita3** [comment]
Escalate in the wrong proposal 

![Image](https://github.com/bosonprotocol/interface/assets/122606799/624c26e8-dffd-49a5-8d1f-75c46b7266fb)

**Comment by sukrita3** [comment]
Retract button disabled in modal

**Comment by sukrita3** [comment]
The back arrow button doesn't work, I guess it should go back to the DR center?

![Image](https://github.com/bosonprotocol/interface/assets/122606799/3256fd7f-62dc-443a-91ac-57c28468290a)

**Comment by sukrita3** [comment]
alignment of the steps

![Image](https://github.com/bosonprotocol/interface/assets/122606799/296115a8-e6b6-4eef-be17-2bb89ee2f4aa)

**Comment by sukrita3** [comment]
skip this screen

![Image](https://github.com/bosonprotocol/interface/assets/122606799/c276025c-53df-4438-ae05-6dc777a1e44a)

**Comment by sukrita3** [comment]
remove skip button

![Image](https://github.com/bosonprotocol/interface/assets/122606799/7602dd04-8338-47bd-aa0c-fbcb3e4e35e8)

**Comment by sukrita3** [comment]
keep font sizes consistent 

![Image](https://github.com/bosonprotocol/interface/assets/122606799/4362f6bf-251a-41bd-b03b-e9231edda6bc)

**Comment by sukrita3** [comment]
there is an error when you hit the 'back arrow' on top left

![Image](https://github.com/bosonprotocol/interface/assets/122606799/7f1b7c09-a4f0-41d2-ae09-5a005b27738b)

**Comment by sukrita3** [comment]
copy change 
![Image](https://github.com/bosonprotocol/interface/assets/122606799/fd845ba3-c394-4f0e-8c82-696d62015dfc)

**Comment by sukrita3** [comment]
copy change

![Image](https://github.com/bosonprotocol/interface/assets/122606799/123e42e9-27c0-4e4c-8f39-1ae6be806dba)

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/interface/assets/122606799/578f94e2-1f49-44bb-b699-56fe3c3e1344)

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/interface/assets/122606799/2931ba28-cdcb-4d93-ac94-17a075268d79)

**Comment by sukrita3** [comment]
COPY: When a buyer raises a dispute they can create a resolution proposal, which sellers can either accept or provide a counterproposal solution to. When an acceptable solution for both parties is found, the dispute will be resolved. If there is no acceptable solution, the buyer can escalate the dispute and it will be resolved by a 3rd party.

![Image](https://github.com/bosonprotocol/interface/assets/122606799/5196da3e-b90d-41ef-bf3e-38a48c5330a6)

**Comment by albertfolch-redeemeum** [comment]
change text depending on party

![image](https://github.com/bosonprotocol/interface/assets/102516373/3ed4d64d-6c7e-4709-8ae9-d4ff25cb8c7b)

**Comment by sukrita3** [comment]
In time bar, change copy to:
24 out of 30 days left to mutually resolve the dispute or escalate

**Comment by sukrita3** [comment]
Is it possible to change the order of the buyer message per figma? so Category, additional info, refund summary

![Image](https://github.com/bosonprotocol/interface/assets/122606799/dd60f4f6-23b7-42ea-91d1-b611baa08c5e)

**Comment by sukrita3** [comment]
should we add a message box for the seller to add some info in the coutnerproposal?

![Image](https://github.com/bosonprotocol/interface/assets/122606799/01f96dfa-a691-48cf-b343-50adcc79d3f0)

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/interface/assets/122606799/ac8b61c2-a157-41dc-a84d-d77d51d29959)

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/interface/assets/122606799/e37a2f6c-2c61-4e52-848f-8279cef20e47)

**Comment by sukrita3** [comment]
is this the graph being slow?


![Image](https://github.com/bosonprotocol/interface/assets/122606799/fc126703-3bf0-4158-8bcb-9f9f4a60e004)

**Comment by albertfolch-redeemeum** [comment]
TODO: add message that's displayed when there are not many days left of the dispute

**Comment by albertfolch-redeemeum** [comment]
TODO: check issue with xmtp when changing wallets
