### ISSUE TITLE
fix regex in custom store links

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#741]
![image](https://github.com/bosonprotocol/interface/assets/102516373/b5873b21-78a5-40e9-beec-1ede1f3425b4)

the regex we use (the text pattern that has to follow the link) doesnt support capital letters after the / and also it doesnt support the =

**Comment by sukrita3** [comment]
@sukrita3 to test throughly

**Comment by albertfolch-redeemeum** [comment]
paused, waiting for Hugo to add related bugs here
