### ISSUE TITLE
Exchange Policy Details issues on offer and exchange details (on both dApp and DR Center)

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/interface#783]
https://bosonapp.io/#/exchange/409
![image](https://github.com/bosonprotocol/interface/assets/7184124/2fb6a0eb-500c-4351-b7a7-0b64da7a6c23)

https://bosonapp.io/#/offers/531
![image](https://github.com/bosonprotocol/interface/assets/7184124/9287da13-8f89-4ba4-8e7c-7536a13d8f2b)

Note: it works on product page

**Comment by albertfolch-redeemeum** [comment]
check https://interface-test.on.fleek.co/#/offers/531
