### ISSUE TITLE
ETH Mainnet deployment + Fiat on-ramp + Network switcher

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#786]

**Comment by sukrita3** [comment]
When a user connects their wallet to the dApp, the user needs to read, understand and accept the dApp’s Privacy Policy and Terms & Conditions (Ts&Cs). The links to the Privacy Policy and the Ts&Cs should be displayed so that the user can access and read before they connect their wallet to use the dApp.


As an example, OpenSea first shows a pop up below:
![Screenshot 2023-08-17 at 12 09 33](https://github.com/bosonprotocol/interface/assets/122606799/d5970645-53ce-4cf0-8a54-b48983ae9539)

OpenSea then shows the links to the Terms and Privacy Policy again on the pop-up screen when the metamask wallet is trying to connect:
![Screenshot 2023-08-17 at 12 10 20](https://github.com/bosonprotocol/interface/assets/122606799/3dc5616a-c468-4e22-a290-bff0df6e94f6)

Uniswap shows in the following screen:
![Screenshot 2023-08-17 at 12 10 47](https://github.com/bosonprotocol/interface/assets/122606799/b41a5a46-3db7-4c35-a347-a113156acfb2)


**Suggest to include the following language in the wallet connect modal (similar to Uniswap) :**

By connecting a wallet, you agree to the Boson dApp's Terms and Conditions (https://bosonapp.io/#/terms-and-conditions) and consent to it's Privacy Policy (https://bosonapp.io/#/privacy-policy).

**Comment by albertfolch-redeemeum** [comment]
I think we can close this @sukrita3 ?

**Comment by sukrita3** [comment]
Yes
