### ISSUE TITLE
Token Swap 

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#799]

**Comment by sukrita3** [comment]
![Screenshot 2023-09-05 at 16 05 18](https://github.com/bosonprotocol/interface/assets/122606799/8ba8d300-c94c-4c74-8bc3-961cf20994c1)

**Comment by sukrita3** [comment]
![Screenshot 2023-09-05 at 16 09 35](https://github.com/bosonprotocol/interface/assets/122606799/18935d37-7ae6-46e1-8b69-9ff5a8f04407)

Pre-populated token and amount should be on the receiving side ...

**Comment by sukrita3** [comment]
![Screenshot 2023-09-05 at 16 41 49](https://github.com/bosonprotocol/interface/assets/122606799/e9a4632f-d8b0-472d-99b0-1de309e1aaaf)

**Comment by sukrita3** [comment]
On the token swap page, when the buyer hits 'Buy', redirect the swap page to the product detail page (new tab with Moonpay Buy should still happen).

**Comment by sukrita3** [comment]
Native token 'not found' when Buy/Swap is selected
![Screenshot 2023-09-18 at 16 49 57](https://gith
![Screenshot 2023-09-18 at 16 51 24](https://github.com/bosonprotocol/interface/assets/122606799/3c6fac74-ad9f-4b4b-bb9f-b8d8b49279e2)
ub.com/bosonprotocol/interface/assets/122606799/f6a33521-5574-45c1-8edd-524214d3acab)

**Comment by sukrita3** [comment]
![Screenshot 2023-09-18 at 16 52 08](https://github.com/bosonprotocol/interface/assets/122606799/3159ac0f-98db-4dc8-98b3-47ae62f49a22)
shorten search bar to keep top nav headers in one line (dont wrap text)

**Comment by albertfolch-redeemeum** [comment]
all these are done, can we close this? @sukrita3
