### ISSUE TITLE
Create Product - token gated offer. The maximum number of Commits should not be over the quantity of items (all variants considered)

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/interface#854]
Examples:
- if I create a single-variant product with a quantity of 1, it should not be possible to set maxCommit to a number greater than 1.
- if I create a multi-variant product (3 variants, with quantities 5, 10 and 15 for each), it should not be possible to set maxCommit to a number greater than 30 (= 5 + 10+ 15).

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/interface/assets/122606799/e3923edc-7d41-4e01-b493-6c6f58a4255f)

**Comment by sukrita3** [comment]
The copy on this has not changed @albertfolch-redeemeum
