### ISSUE TITLE
relist offer completely 

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#857]
when you click on relist offer in the seller hub, you should be redirected to the create product page with all the fields prepolulated from the existing offer

**Comment by sukrita3** [comment]
![Screenshot 2023-10-04 at 13 50 55](https://github.com/bosonprotocol/interface/assets/122606799/a7602b09-2326-4bb7-944a-877bdf0cde64)

When relisting a single variant item, and then changing it to one with variants, the original token and amounts show up under an 'Unknown' variant name. Experience should be no information is show on token/amount/qty, etc.

**Comment by sukrita3** [comment]
![Screenshot 2023-10-04 at 13 57 10](https://github.com/bosonprotocol/interface/assets/122606799/4213aac9-ea92-435d-aeaa-1fc9ac7bebaf)
Left align Qty/Available values
