### ISSUE TITLE
tokens are not loading in testing/staging/production because origin header is not uniswap

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#866]
![image](https://github.com/bosonprotocol/interface/assets/102516373/94609714-2e87-4938-8ffc-bfa2ca9e3277)

**Comment by albertfolch-redeemeum** [comment]
instead of trying to bypass this limitation, load the tokens we support only

**Comment by sukrita3** [comment]
Looks good
