### ISSUE TITLE
dApp - Default to no expiration date on offers

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#886]

**Comment by sukrita3** [comment]
https://miro.com/app/board/uXjVMjOt-yc=/?share_link_id=430655545822

**Comment by albertfolch-redeemeum** [comment]
@sukrita3 let's discuss the copy changes

**Comment by sukrita3** [comment]
![Screenshot 2023-11-03 at 15 25 05](https://github.com/bosonprotocol/interface/assets/122606799/d4809f6d-ccf6-453e-8903-06b68ec1a493)

**Comment by sukrita3** [comment]
![Screenshot 2023-11-03 at 15 27 01](https://github.com/bosonprotocol/interface/assets/122606799/0fa3139c-9f8c-4d9c-a008-470341e59dd6)

**Comment by sukrita3** [comment]
![Screenshot 2023-11-03 at 15 31 44](https://github.com/bosonprotocol/interface/assets/122606799/018e7c39-43ce-4d1d-b02b-e2bac6de4373)

**Comment by sukrita3** [comment]
![Screenshot 2023-11-03 at 15 33 00](https://github.com/bosonprotocol/interface/assets/122606799/78368aee-f0b1-44bb-890d-31ef9263cd8e)

**Comment by sukrita3** [comment]
![Screenshot 2023-11-03 at 15 41 16](https://github.com/bosonprotocol/interface/assets/122606799/e05bfbef-8bfe-4451-a5af-f0cad8602bff)

**Comment by sukrita3** [comment]
![Screenshot 2023-11-03 at 15 43 32](https://github.com/bosonprotocol/interface/assets/122606799/bccd67ab-446d-42e1-a166-baa2d465a926)

**Comment by albertfolch-redeemeum** [comment]
> ![Screenshot 2023-11-03 at 15 27 01](https://user-images.githubusercontent.com/122606799/280309005-0fa3139c-9f8c-4d9c-a008-470341e59dd6.png)

they were already required (I checked in test)

**Comment by albertfolch-redeemeum** [comment]
> ![Screenshot 2023-11-03 at 15 43 32](https://user-images.githubusercontent.com/122606799/280314835-bccd67ab-446d-42e1-a166-baa2d465a926.png)

what should be the new copy?

**Comment by sukrita3** [comment]
Copy for Redeemable for:
OLD: If you don't redeem your NFT during the redemption period, it will expire and you will receive back the price minus the Buyer cancel penalty.

NEW: Your NFT is available for redemption during this period, calculated from the date it was committed. If you do not redeem the NFT in this period, it will expire and you will receive back the price minus the buyer cancellation penalty.
