### ISSUE TITLE
hide chat messages that tell that the exchange/dispute status changed but didnt in the end

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#887]
if I try to escalate, the chat message is first sent and then the escalation is done... if the escalation is NOT done in the end, the chat message would already be there (wrong in this case)

solution: 

- hide escalation messages if there is no escalationDate in the exchange OR
- send another message saying it went wrong <- we'll do this

PS: same situation with retract and other actions

**Comment by sukrita3** [comment]
use case for retract and escalate. but there is no use if we send another proposal (message not sent until signed)
