### ISSUE TITLE
dApp - sellers prompted to deposit funds when no seller deposit has been selected for offers [ETH + Polygon]

### ISSUE THREAD

**Issue by hugoallen** [bosonprotocol/interface#892]
![image (5)](https://github.com/bosonprotocol/interface/assets/128500865/f2cc0b15-c9cc-49b4-8b0e-ea80f6b867f9)
![IMG_4259](https://github.com/bosonprotocol/interface/assets/128500865/b72add87-a147-4477-8b23-2d0bef45ea7b)

**Comment by albertfolch-redeemeum** [comment]
to get the first product of the second image above:
https://api.thegraph.com/subgraphs/name/bosonprotocol/polygon/graphql?query=%7B%0A++productV1Products%28where%3A+%7Buuid_starts_with_nocase%3A+%22d3fd%22%7D%29+%7B%0A++++id%0A++++uuid%0A++++variants+%7B%0A++++++offer+%7B%0A++++++++metadata+%7B%0A++++++++++name%0A++++++++%7D%0A++++++++seller%7B%0A++++++++++admin%0A++++++++++assistant%0A++++++++%7D%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D
