### ISSUE TITLE
update (buyer/seller contract, rNFT etc) contracts and help section in create product flow for offers with no expiration

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#907]

**Comment by sukrita3** [comment]
@albertfolch-redeemeum help text: https://docs.google.com/document/d/12YMB_GtW7I_oN4H9srArFitOZf2E4lL24GxSoJI3H3k/edit#heading=h.6x6yvavklx79

**Comment by sukrita3** [comment]
dApp Terms & Conditions:

**Comment by sukrita3** [comment]
**Please noted one minor correction needed in the live version of the Privacy Policy:

Under 3.1.2, delete the comma and the word “and”, and replace them with a period.**

information about your use of the Services.
