### ISSUE TITLE
Phygitals MVP

### ISSUE THREAD

**Issue by sukrita3** [bosonprotocol/interface#927]

**Comment by sukrita3** [comment]
https://miro.com/app/board/uXjVNOQiFwM=/

**Comment by albertfolch-redeemeum** [comment]
waiting on the legal documents before continuing

**Comment by sukrita3** [comment]
https://miro.com/app/board/uXjVNOQiFwM=/?moveToWidget=3458764583983118423&cot=14

**Comment by sukrita3** [comment]
https://miro.com/app/board/uXjVNOQiFwM=/?moveToWidget=3458764583983248785&cot=14

**Comment by sukrita3** [comment]
https://miro.com/app/board/uXjVNOQiFwM=/?moveToWidget=3458764583984883731&cot=14

**Comment by sukrita3** [comment]
https://miro.com/app/board/uXjVNOQiFwM=/?moveToWidget=3458764583984883731&cot=14
