### ISSUE TITLE
integrate react component of the commit widget into the PDP and update also PDP bottom design

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/interface#993]
new PDP bottom part design:
![image](https://github.com/bosonprotocol/interface/assets/102516373/9161e429-7f59-4e19-adbd-0cacd675a93d)

https://www.figma.com/file/M7bh6PAel8HaDE4Y3bukQT/v2-dApp-Master-file-(Balint's-Copy)?mode=dev

the react component of the commit widget is the white rectangle where you see the price, etc and it has changed

**Comment by albertfolch-redeemeum** [comment]
focus the testing on:

token gating (create an offer for each combination)
product detail page PDP (check details and rnft and buyer&seller contracts)
create an offer with variants with all the images and see how it looks (8 images different for each one) + video
create an offer with variants with all the images and see how it looks (but all the variants with the same images, 8) + video
create an offer with NO variants with all the images and see how it looks + video
check expired offers, voided, etc

**Comment by sukrita3** [comment]
It is hard to tell if the gate icon is locked or unlocked, should we try to make it bigger?

![Image](https://github.com/bosonprotocol/interface/assets/122606799/0c8535e3-14a1-4204-8bdc-f87c61e4bb8c)
